AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Lambda functions for recurring BTC and ETH purchases

Parameters:
  CodeBucket:
    Type: String
    Description: S3 bucket containing Lambda code
  LambdaRuntime:
    Type: String
    Description: Python runtime version for Lambda functions
    Default: python3.13
  RecurringBuyBTCCodeKey:
    Type: String
    Description: S3 key for RecurringBuyBTC code
    Default: recurring-buy-btc.zip
  RecurringBuyETHCodeKey:
    Type: String
    Description: S3 key for RecurringBuyETH code
    Default: recurring-buy-eth.zip

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - "arn:aws:ssm:us-east-1:137530478974:parameter/GeminiApiKeys"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: "arn:aws:kms:us-east-1:137530478974:key/*"

  RecurringBuyBTC:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RecurringBuyBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref RecurringBuyBTCCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 128

  RecurringBuyETH:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RecurringBuyETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref RecurringBuyETHCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 128

Outputs:
  RecurringBuyBTCArn:
    Value: !GetAtt RecurringBuyBTC.Arn
  RecurringBuyETHArn:
    Value: !GetAtt RecurringBuyETH.Arn