AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy multiple Lambda functions for crypto-autobuy and autosell

Parameters:
  CodeBucketName:
    Type: String
    Description: S3 bucket containing Lambda code
  LambdaRuntime:
    Type: String
    Description: Python runtime version for Lambda functions
    Default: python3.13
  ConvertGUSDCodeKey:
    Type: String
    Description: S3 key for ConvertGUSD code
    Default: placeholder.zip
  ManualBuyBTCCodeKey:
    Type: String
    Description: S3 key for ManualBuyBTC code
    Default: placeholder.zip
  ManualBuyETHCodeKey:
    Type: String
    Description: S3 key for ManualBuyETH code
    Default: placeholder.zip
  RecurringBuyBTCCodeKey:
    Type: String
    Description: S3 key for RecurringBuyBTC code
    Default: placeholder.zip
  RecurringBuyETHCodeKey:
    Type: String
    Description: S3 key for RecurringBuyETH code
    Default: placeholder.zip
  ManualSellBTCCodeKey:
    Type: String
    Description: S3 key for ManualSellBTC code
    Default: placeholder.zip
  ManualSellETHCodeKey:
    Type: String
    Description: S3 key for ManualSellETH code
    Default: placeholder.zip

Resources:
  CodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CodeBucketName
      AccessControl: Private

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - "arn:aws:ssm:us-east-1:137530478974:parameter/GeminiApiKeys"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: "arn:aws:kms:us-east-1:137530478974:key/*"

  ConvertGUSD:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: ConvertGUSD
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref ConvertGUSDCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  ManualBuyBTC:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: ManualBuyBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref ManualBuyBTCCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  ManualBuyETH:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: ManualBuyETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref ManualBuyETHCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  RecurringBuyBTC:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: RecurringBuyBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref RecurringBuyBTCCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  RecurringBuyETH:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: RecurringBuyETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref RecurringBuyETHCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  ManualSellBTC:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: ManualSellBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref ManualSellBTCCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

  ManualSellETH:
    Type: AWS::Lambda::Function
    DependsOn: CodeBucket
    Properties:
      FunctionName: ManualSellETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: !Ref ManualSellETHCodeKey
      Runtime: !Ref LambdaRuntime
      Timeout: 30
      MemorySize: 256

Outputs:
  CodeBucketName:
    Value: !Ref CodeBucketName
  ConvertGUSDArn:
    Value: !GetAtt ConvertGUSD.Arn
  ManualBuyBTCArn:
    Value: !GetAtt ManualBuyBTC.Arn
  ManualBuyETHArn:
    Value: !GetAtt ManualBuyETH.Arn
  RecurringBuyBTCArn:
    Value: !GetAtt RecurringBuyBTC.Arn
  RecurringBuyETHArn:
    Value: !GetAtt RecurringBuyETH.Arn
  ManualSellBTCArn:
    Value: !GetAtt ManualSellBTC.Arn
  ManualSellETHArn:
    Value: !GetAtt ManualSellETH.Arn