AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda functions for recurring BTC and ETH purchases

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - "arn:aws:ssm:us-east-1:137530478974:parameter/GeminiApiKeys"

  RecurringBuyBTC:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Dependencies: recurring-buy-btc/requirements.txt
    Properties:
      FunctionName: RecurringBuyBTC
      Handler: recurring-buy-btc.function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: .
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128

  RecurringBuyETH:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
      BuildProperties:
        Dependencies: recurring-buy-eth/requirements.txt
    Properties:
      FunctionName: RecurringBuyETH
      Handler: recurring-buy-eth.function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: .
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128

Outputs:
  RecurringBuyBTCArn:
    Value: !GetAtt RecurringBuyBTC.Arn
  RecurringBuyETHArn:
    Value: !GetAtt RecurringBuyETH.Arn