AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy multiple Lambda functions for crypto-autobuy

Parameters:
  CodeBucket:
    Type: String
    Description: S3 bucket containing Lambda code
  ConvertGUSDCodeKey:
    Type: String
    Description: S3 key for ConvertGUSD code
    Default: convert-gusd.zip
  ManualBuyBTCCodeKey:
    Type: String
    Description: S3 key for ManualBuyBTC code
    Default: manual-buy-btc.zip
  ManualBuyETHCodeKey:
    Type: String
    Description: S3 key for ManualBuyETH code
    Default: manual-buy-eth.zip
  RecurringBuyBTCCodeKey:
    Type: String
    Description: S3 key for RecurringBuyBTC code
    Default: recurring-buy-btc.zip
  RecurringBuyETHCodeKey:
    Type: String
    Description: S3 key for RecurringBuyETH code
    Default: recurring-buy-eth.zip
  ManualSellBTCCodeKey:
    Type: String
    Description: S3 key for ManualSellBTC code
    Default: manual-sell-btc.zip
  ManualSellETHCodeKey:
    Type: String
    Description: S3 key for ManualSellETH code
    Default: manual-sell-eth.zip

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "arn:aws:secretsmanager:us-east-1:137530478974:secret:GeminiApiKeys-uNQ040"

  ConvertGUSD:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ConvertGUSD
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref ConvertGUSDCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  ManualBuyBTC:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ManualBuyBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref ManualBuyBTCCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  ManualBuyETH:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ManualBuyETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref ManualBuyETHCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  ManualSellBTC:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ManualSellBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref ManualSellBTCCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  ManualSellETH:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ManualSellETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref ManualSellETHCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  RecurringBuyBTC:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RecurringBuyBTC
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref RecurringBuyBTCCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

  RecurringBuyETH:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RecurringBuyETH
      Handler: function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref RecurringBuyETHCodeKey
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128

Outputs:
  ConvertGUSDArn:
    Value: !GetAtt ConvertGUSD.Arn
  ManualBuyBTCArn:
    Value: !GetAtt ManualBuyBTC.Arn
  ManualBuyETHArn:
    Value: !GetAtt ManualBuyETH.Arn
  ManualSellBTCArn:
    Value: !GetAtt ManualSellBTC.Arn
  ManualSellETHArn:
    Value: !GetAtt ManualSellETH.Arn
  RecurringBuyBTCArn:
    Value: !GetAtt RecurringBuyBTC.Arn
  RecurringBuyETHArn:
    Value: !GetAtt RecurringBuyETH.Arn