AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda function for recurring BTC and ETH purchases with error email notifications

Parameters:
  PurchaseSchedule:
    Type: String
    Default: cron(0 8 ? * SUN *)
    Description: Cron expression for recurring BTC and ETH purchase schedule

  NotificationEmail:
    Type: String
    Default: kpd@duck.com
    Description: Email address to receive alerts

  LambdaRuntime:
    Type: String
    Default: python3.14
    Description: Lambda runtime for RecurringBuyCrypto (e.g. python3.12, python3.13, python3.14)

Resources:
  # SNS Topic for Alerts
  CryptoBuyAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: CryptoBuyAlerts
      DisplayName: "Crypto Buy Lambda Alerts"

  CryptoBuyAlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref CryptoBuyAlertTopic
      Endpoint: !Ref NotificationEmail

  # IAM Role for Lambda and Scheduler
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/GeminiApiKeys"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref CryptoBuyAlertTopic
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RecurringBuyCrypto"

  # Lambda function for recurring crypto purchases
  RecurringBuyCrypto:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RecurringBuyCrypto

      Handler: recurring_buy_crypto.lambda_handler

      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: .

      Runtime: !Ref LambdaRuntime

      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref CryptoBuyAlertTopic

  # Schedule for invoking recurring crypto purchases
  RecurringBuyCryptoSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: RecurringBuyCrypto_Schedule
      Description: Invoke RecurringBuyCrypto for BTC and ETH
      GroupName: default
      ScheduleExpression: !Ref PurchaseSchedule
      ScheduleExpressionTimezone: America/New_York
      FlexibleTimeWindow:
        Mode: "OFF"
      State: ENABLED
      Target:
        Arn: !GetAtt RecurringBuyCrypto.Arn
        RoleArn: !GetAtt LambdaExecutionRole.Arn
        Input: '{}'

  # Permission for Scheduler to invoke RecurringBuyCrypto
  RecurringBuyCryptoPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RecurringBuyCrypto.Arn
      Action: lambda:InvokeFunction
      Principal: scheduler.amazonaws.com
      SourceArn: !Sub arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/RecurringBuyCrypto_Schedule
    DependsOn:
      - RecurringBuyCryptoSchedule
      - RecurringBuyCrypto

Outputs:
  RecurringBuyCryptoArn:
    Value: !GetAtt RecurringBuyCrypto.Arn
  AlertTopicArn:
    Value: !Ref CryptoBuyAlertTopic