AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy Lambda functions for recurring BTC and ETH purchases

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/GeminiApiKeys"
              - Effect: Allow
                Action:
                  - scheduler:CreateSchedule
                  - scheduler:ListSchedules
                  - scheduler:GetSchedule
                  - scheduler:UpdateSchedule
                  - scheduler:DeleteSchedule
                  - scheduler:CreateScheduleGroup
                  - scheduler:ListScheduleGroups
                  - scheduler:GetScheduleGroup
                  - scheduler:DeleteScheduleGroup
                Resource: '*'

  RecurringBuyBTC:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RecurringBuyBTC
      Handler: recurring-buy-btc.function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: .
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128

  RecurringBuyETH:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RecurringBuyETH
      Handler: recurring-buy-eth.function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: .
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128

  RecurringBuyBTCPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RecurringBuyBTC.Arn
      Action: lambda:InvokeFunction
      Principal: scheduler.amazonaws.com
      SourceArn: !Sub arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/RecurringBuyBTC_Schedule

  RecurringBuyETHPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt RecurringBuyETH.Arn
      Action: lambda:InvokeFunction
      Principal: scheduler.amazonaws.com
      SourceArn: !Sub arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/RecurringBuyETH_Schedule

  RecurringBuyBTCSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: RecurringBuyBTC_Schedule
      Description: Invoke RecurringBuyBTC every Sunday at 11 AM EST
      ScheduleExpression: cron(0 11 ? * SUN *)
      ScheduleExpressionTimezone: America/New_York
      FlexibleTimeWindow:
        Mode: "OFF"
      State: ENABLED
      Target:
        Arn: !GetAtt RecurringBuyBTC.Arn
        RoleArn: !GetAtt LambdaExecutionRole.Arn
        Input: '{}'

  RecurringBuyETHSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: RecurringBuyETH_Schedule
      Description: Invoke RecurringBuyETH every Sunday at 11 AM EST
      ScheduleExpression: cron(0 11 ? * SUN *)
      ScheduleExpressionTimezone: America/New_York
      FlexibleTimeWindow:
        Mode: "OFF"
      State: ENABLED
      Target:
        Arn: !GetAtt RecurringBuyETH.Arn
        RoleArn: !GetAtt LambdaExecutionRole.Arn
        Input: '{}'

Outputs:
  RecurringBuyBTCArn:
    Value: !GetAtt RecurringBuyBTC.Arn
  RecurringBuyETHArn:
    Value: !GetAtt RecurringBuyETH.Arn